name: Merge Main Into Alpha

on:
  push:
    branches:
      - 'main'

jobs:
  main:
    name: Create PR Release to Alpha
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      # https://github.com/marketplace/actions/github-pull-request-action
      - name: create pull request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          destination_branch: 'alpha'
          pr_title: '[Automated] Merge ${{ github.ref_name }} into Alpha'
          pr_body: 'Automated Pull Request'
          pr_label: 'auto-merge'

      # https://github.com/marketplace/actions/pull-request-merge
      - name: enable automerge
        uses: sudo-bot/action-pull-request-merge@v1.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.open-pr.outputs.pr_number }}
          merge-method: merge
